### ISSUE TITLE
Backbone validation doesn't support model associations

### ISSUE THREAD

**Issue by pierre-duchesne** [resthub/resthub-backbone-stack#121]
I can reproduce this problem on my project with resthub (backbone validation + backbone relational).

https://github.com/thedersen/backbone.validation/pull/125

I had to apply this pull request in my project.

**Comment by sdeleuze** [comment]
Is it a new issue or did that occur with previous Backbone stack ?

**Comment by pierre-duchesne** [comment]
Its a new issue. (In the new version of backbone-validation.js)

**Comment by sdeleuze** [comment]
Does it fix the issue in you apply manually this patch ?
https://github.com/magnusvk/backbone.validation/commit/70f20fc0aab32cb66fbb4d88d0cae2ad036f795e

**Comment by pierre-duchesne** [comment]
yes :)
