### ISSUE TITLE
Gestion de backbone validation

### ISSUE THREAD

**Issue by axlbonnet** [resthub/resthub-backbone-stack#134]
Actuellement, la vue resthub unbind backbone-validation lors de tout appel à "stopListening" (qui est appelé à le destruction de la vue).

Cela pose problème : si un model est attaché à 2 vue A et B, et que backbone-validation est bindé sur la la vue B, la destruction de la vue A (où tout appel à stopListening au sein de la vue A) désactivera la validation sur la vue B.

De mon point de vue, ou Resthub s'occupe du "unbind" et du "bind", ou d'aucun des 2.
L'appel au unbind a certainement été parce le développeur n'y pense jamais et que cela laissé un lien du model vers une vue qui provoquait une fuite mémoire.
Une première amélioration serait de faire ce "unbind" lors de la destruction de la vue, et non pas lors de tout appel à "stopListening".

Une autre proposition serait de déléguer le binding model/vue de Backbone-validation à resthub.

Au lieu de faire.

``` javascript
Backbone.Validation.bind(this);
```

Faire :

``` javascript
this.bindValidation();
```

Resthub sauvegarderait alors dans le model la vue associée. Et à la destruction d'une vue, le "unbind" serait fait uniquement si c'est nécessaire. Idem pour colection.

**Comment by sdeleuze** [comment]
Implemented a better unbind, but no nice solution for bind so I let it on application developer side
