### ISSUE TITLE
AjaxError event triggered without error

### ISSUE THREAD

**Issue by jycamier** [resthub/resthub-backbone-stack#137]
When there is the synchronization activated on a backbone model  (Resthub.Validation), sometimes Jquery triggers an ajaxError event with a status code 200. 
That’s happened on the following cases :
-   The java model enquired in the className attribute (Backbone.model) is an abstract class ;
-   The java model enquired in the className attribute (Backbone.model) hasn’t got any validation’s constraints.
  In the both cases, the server answer is empty.

**Comment by sdeleuze** [comment]
Replaced by https://github.com/resthub/resthub-spring-stack/issues/206 on spring stack side
