### ISSUE TITLE
project created with archtype org.resthub:resthub-jpa-backbonejs-multi-archetype does not work

### ISSUE THREAD

**Issue by pochadri** [resthub/resthub-backbone-stack#151]
project created with archtype org.resthub:resthub-jpa-backbonejs-multi-archetype not wotrking .

after creating the project and running jetty not able to get any result accessing <URL>/api/sample

**Comment by sdeleuze** [comment]
Tested on my side with 2.1.2, it works ... 
Please try to run mvn jetty:run from webapp folder, not root, since it is a multi module project ...

**Comment by pochadri** [comment]
my bad for ignoring that, it runs from webapp folder.
thanks.

gone through the complete tutorial and i must say that everything is well documented and it was a breeze to go through the complete example and understand it. The whole framework also looks good with nice support for testing.

please let me know if i can contribute to this project in anyway.

regards
