### ISSUE TITLE
Improve View.render() behaviour when using model or collection callback

### ISSUE THREAD

**Issue by sdeleuze** [resthub/resthub-backbone-stack#51]
Make it possible this to work by default :
this.collection.fetch({ success: this.render });

Currently render does not work well since a model or object instance is passed as parameter.
My proposal : when we detect that the parameter is an instance of Model or Collection, we pass to the rendering context model.toJSON() or collection.toJSON()

Any thoughts ?

**Comment by loicfrering** [comment]
I think that we should give priority to binding a reset event instead of passing a success callback in fetch:

``` javascript
this.collection.on('reset', this.render);
```

Still the issue remains true but only if this.model and this.collection are undefined in the view, do you agree?

I'll try to find a convenient solution for the case where we do not pass a model neither a collection to the view using the appropriate options.

**Comment by loicfrering** [comment]
Ok so in fact the arguments passed to this.render take priority over this.model and this.collection. Also fetch is passing the collection to the success callback (as well as the reset event triggers the callback with the collection as first parameter), so the collection will be the context in this case and everything should be working as expected and as long as you expect the context to be the collection.

So, as far as I can tell, your problem only occurs when you specify a custom context in this.context, isn't it ? Or do I miss an other use case?

**Comment by sdeleuze** [comment]
Sorry for the wrong sample, I wanted to talk about reset event like you, not success callback to fetch.

The issue is that when you define this.collection.on('reset', this.render), the argument passed as parameter of the render function effectively take priority on this.model and this.collection, but the important point is that this is a Backbone Model or Collection, not a JSON context object.

The fix I propose is : when render first parameter is a Model or Collection, we put in the context arg.toJSON(), not directly arg ...

**Comment by sdeleuze** [comment]
The other option is : never take in account (by default) render arguments, and provide a default getContext() function that people will extend like they want. The new render() implementation will use getContext() in all case to retreive the context().

I think I prefer this option 2 since it could be used even in real life (complex applications) use cases ...

**Comment by loicfrering** [comment]
Ok I see, thank you for the clarification.

I think that the first option is the good one: trying to call context.toJSON() if context.toJSON is defined even if the context is passed directly.

For the 2nd option, I am not really sure if it is a good idea for now. If you agree, I'd like to go with the first option and eventually reopen this issue if we experience strong use cases for getContext().

**Comment by sdeleuze** [comment]
Ok fine for me, thanks !
