### ISSUE TITLE
Test (and eventually fix) the stack on IE7 and IE8

### ISSUE THREAD

**Issue by sdeleuze** [resthub/resthub-backbone-stack#54]
We should check that Backbone, Underscore and RESThub stack tests pass on these 2 browsers

**Comment by johanpoirier** [comment]
console.log() is not compatible with IE7.
We have to handle that.

**Comment by sdeleuze** [comment]
Assign to Baptiste since a is one who got an old IE.

We may ask to Florian how to handle IE7 issue ...

**Comment by bmeurant** [comment]
I'll test on IE8 but I don't have any IE7 in my pocket :-)

**Comment by johanpoirier** [comment]
I have IE7 running on XP Mode with Virtual PC. I'll test it next week.

**Comment by sdeleuze** [comment]
I discussed with Florian, he gaves use some hints for fixing console.js on IE7, based on what he did on Archetype : https://bitbucket.org/temsa/archetype-main/src/7507207c7b944b00ca6fb3d4f8efea5ade592f3c/src/main/webapp/Archetype/logger/firebugLogger.js?at=default

console.log and other aliases is not always a function, but sometimes an Object. We should add an catch Exception like they did in Archetype.

**Comment by bmeurant** [comment]
fixed by #96
