### ISSUE TITLE
Provide a config file for r.js optimization.

### ISSUE THREAD

**Issue by johanpoirier** [resthub/resthub-backbone-stack#67]
Go to http://requirejs.org/docs/optimization.html#wholeproject for more information.

Without the config file, Require.js optimization is useless.

**Comment by sdeleuze** [comment]
+1

**Comment by johanpoirier** [comment]
Done in the backbonejs archetype.

Should we provide a config file in the resthub-backbone-stack ? if not, we can remove the r.js file.

**Comment by sdeleuze** [comment]
Yes, we should !

**Comment by johanpoirier** [comment]
Pull Request #73.
