### ISSUE TITLE
Update to Backbone 0.9.10

### ISSUE THREAD

**Issue by sdeleuze** [resthub/resthub-backbone-stack#89]
http://backbonejs.org/#changelog

Backbone.ajax will be great for security mgmt
We should review our guidelines to see if there is some change

Interesting point : "Backbone object now extends Events so that you can use it as a global event bus, if you like." so it may be a good idea to replace PubSub by using Backbone as a global event bus.

**Comment by sdeleuze** [comment]
As a dependency, Underscore should be upgraded to 1.4.3, o maybe we could use Lo-Dash (better browser compatibility + performances) http://lodash.com/

**Comment by sdeleuze** [comment]
Validation behaviour has changed, this may impact our Validation related extensions

**Comment by sdeleuze** [comment]
Another reason for using Backbone instead of jQuery custom event for event bus : http://jsperf.com/events-vs-events2/8

**Comment by bclozel** [comment]
Aaaand 0.9.10 is out, with a lot of changes that sound familiar...
Previous changes are still [there](https://github.com/documentcloud/backbone/blob/0.9.9/index.html#L618)

**Comment by sdeleuze** [comment]
Have began to update to 0.9.10, including bb raltional and validation plugin update.
@bmeurant Could you have a look to my fork https://github.com/sdeleuze/resthub-backbone-stack
I have some validation tests not working anymore ...

Since Backbone now extends Backbone.Events, I have removed PubSub and used Backbone instead ...

**Comment by sdeleuze** [comment]
Also upgraded to jQuery 1.9.1, Bootstrap 2.3, Underscore 1.4.4 and RequireJS 2.1.4
